apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/label: "python3-agent"   # Jenkins will match on this label
spec:
  serviceAccountName: jenkins-deployer      # must exist in the "apps" namespace
  containers:
    # For python testing
    - name: python
      image: python:3.11
      command: ["cat"]
      tty: true
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: workspace
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"

    # For building docker containers and publishing to GHCR
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command: ["cat"]
      tty: true
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: workspace
        - mountPath: /kaniko/.docker
          name: docker-config
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "4Gi"

    # For deploying to the k3s cluster
    - name: kubectl
      image: bitnami/kubectl:latest
      command: ["cat"]
      tty: true
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: workspace
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"

  volumes:
    - name: workspace
      emptyDir: {}
    - name: docker-config
      secret:
        secretName: reg-creds
